name: recipe-generator

services:
  db:
    image: postgres:16
    restart: unless-stopped
    container_name: recipe-generator-postgress
    environment:
      POSTGRES_DB: ${PGDATABASE:-recipe_generator}
      POSTGRES_USER: ${PGUSER:-recipe_admin}
      POSTGRES_PASSWORD: ${PGPASSWORD:-postgres_password}
    ports:
      - "${PGPORT:-5432}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${PGUSER:-recipe_admin} -d ${PGDATABASE:-recipe_generator}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:
